### ISSUE TITLE
请问有数据库表信息吗

### ISSUE THREAD

**Issue by a1667834841** [ProudMuBai/GoFilm#1]

**Comment by ProudMuBai** [comment]
有的, mysql的表是使用gorm自动创建的, 在部署的时候也将mysql和redis的端口做了映射可以通过客户端工具进行连接查看的, 表信息和连接相关的说明已简单更新到了server目录下的README文件中, 有其他需要了解的到我的博客加我TG也行
https://github.com/ProudMuBai/GoFilm/blob/main/server/README.md

**Comment by a1667834841** [comment]
看到了 十分感谢
