### ISSUE TITLE
film_api启动报错了

### ISSUE THREAD

**Issue by lovefan-fan** [ProudMuBai/GoFilm#10]
[error] failed to initialize database, got error dial tcp 192.168.96.2:3306: connect: connection refused
panic: dial tcp 192.168.96.2:3306: connect: connection refused

goroutine 1 [running]:
main.init.0()
	/opt/server/main.go:22 +0x52

**Comment by ProudMuBai** [comment]
这个是 mysql 容器还没初始化完成造成的, 可以将main.go 中 init 方法的 time.Sleep(time.Second * 20) 这个时间稍微延长一下, 也可以清空redis库中的内容然后 单独执行 docker restart film_api  重启film_api这个容器重新开始获取数据
