### ISSUE TITLE
播放视频报错The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by mouse0524** [ProudMuBai/GoFilm#12]
播放视频报错The media could not be loaded, either because the server or network failed or because the format is not supported.
我看了下博主给的演示环境也是这样

**Comment by Miao089** [comment]
关掉梯子，CDN加速仅限国内

**Comment by ProudMuBai** [comment]
> 播放视频报错The media could not be loaded, either because the server or network failed or because the format is not supported. 我看了下博主给的演示环境也是这样

楼上说的是对的, 因为有些视频存储站那边对其他国家ip做了限制, 所以观看的时候如果使用的是代理IP进行视频数据请求的就会出现这提示
