### ISSUE TITLE
每月28号清库之后好多东西都没了，怎么重新采集回来呢

### ISSUE THREAD

**Issue by lovefan-fan** [ProudMuBai/GoFilm#13]

**Comment by ProudMuBai** [comment]
> 好像重启就重新采集了

StartSpiderRe 这个方法执行的是先清除完数据然后重新进行一次完整的采集,
其实线上的话建议还是把这个重新全采的取消掉, 一般多几个月可以执行一次, 不过这版也快用不到了, 后面应该是放到后台去自己选择性执行了

**Comment by mouse0524** [comment]
> > 好像重启就重新采集了
> 
> StartSpiderRe 这个方法执行的是先清除完数据然后重新进行一次完整的采集, 其实线上的话建议还是把这个重新全采的取消掉, 一般多几个月可以执行一次, 不过这版也快用不到了, 后面应该是放到后台去自己选择性执行了

啥时候法新版啊

**Comment by ProudMuBai** [comment]
> > > 好像重启就重新采集了
> > 
> > 
> > StartSpiderRe 这个方法执行的是先清除完数据然后重新进行一次完整的采集, 其实线上的话建议还是把这个重新全采的取消掉, 一般多几个月可以执行一次, 不过这版也快用不到了, 后面应该是放到后台去自己选择性执行了
> 
> 啥时候法新版啊

后台采集相关的几个基本功能都做了, 还在测试和完善, 大概一周左右会更新上后台, 其他功能后面也会慢慢加上去
