### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by adminlove520** [ProudMuBai/GoFilm#14]
您好  docker-compose 部署 一直报服务器繁忙，请稍后再试

**Comment by adminlove520** [comment]
![image](https://github.com/ProudMuBai/GoFilm/assets/32920883/b5eba622-7772-47fb-b8c7-4933bffc633c)

**Comment by adminlove520** [comment]
请问是不只能部署在国内云主机呀   国外的经常报获取数据失败  请求异常  而且很慢

**Comment by ProudMuBai** [comment]
> 请问是不只能部署在国内云主机呀 国外的经常报获取数据失败 请求异常 而且很慢

应该是服务器性能上的原因吧, Redis连接超时了, 至于采集失败应该是站点那边设置的, 我的演示站点就是New York的
