### ISSUE TITLE
搭建后会提示 导航分类信息获取失败

### ISSUE THREAD

**Issue by foreversnowy** [ProudMuBai/GoFilm#17]
client和server连上了，后台可以打开，开启采集后没有采集成功，前端提示导航分类信息获取失败

**Comment by foreversnowy** [comment]
使用的是v1.1最新版

**Comment by ProudMuBai** [comment]
> 提示导航分类信息获取失败
应该是采集站那边接口返回的时候出问题了,  使用重置采集分类信息按钮就可以了, 另外必须设置主站点然后采集, 前台才会有数据

**Comment by foreversnowy** [comment]
好的，谢谢，我试试

**Comment by Kevin5010** [comment]
我告诉你这个问题了困扰我几个小时，其实是你反向代理不对，反向代理应该是目录是 /api/, 而不是/api,反向内部地址是http://127.0.0.1:3601/，而不是http:// 127.0.0.1:3601

**Comment by Kevin5010** [comment]
并且作者写的也不正确，如果作者同意我可以写一个详细非docker编译搭建的教程

**Comment by foreversnowy** [comment]
后面设置主站点后解决了，哈哈哈

**Comment by ProudMuBai** [comment]
> 并且作者写的也不正确，如果作者同意我可以写一个详细非docker编译搭建的教程

有提供其他安装方式的教程是可以的, 选择用docker也是因为方便, 而且这个反代也说不上错误, 和分类获取失败也没有联系, 只是单纯的将所有/api路径的请求转发到server服务处理而已, 实测是没有问题的
