### ISSUE TITLE
没数据的时候，页面没任何内容

### ISSUE THREAD

**Issue by starfork** [ProudMuBai/GoFilm#27]
https://m.mubai.link/filmClassifySearch?Category=8&Language=%E7%B2%A4%E8%AF%AD&Pid=1&Sort=update_stamp&Year=2024&current=1

没数据，感觉应该保留分类部分，而不是全部“清空”

**Comment by ProudMuBai** [comment]
@starfork 
这个问题我看了确实应该保留上面的标签部分, 已经修复了, 应该是过几天等首页轮播测区域一起更新了
