### ISSUE TITLE
方便问下采集哪里的数据呢？

### ISSUE THREAD

**Issue by yoorxee** [ProudMuBai/GoFilm#31]
Hi~新年好！
方便问下采集哪里的数据呢？

**Comment by ProudMuBai** [comment]
有提供数据源的采集站, 这些需要自己去了解, 内置的也有一些采集站, 直接使用也可以

**Comment by yoorxee** [comment]
> 有提供数据源的采集站, 这些需要自己去了解, 内置的也有一些采集站, 直接使用也可以

问题有一些电影，看着看着就卡着了，而且跳不过去，比如https://m.mubai.link/play?id=82276&source=0&episode=0
7分多 就卡着了 过不去了

**Comment by ProudMuBai** [comment]
> > 有提供数据源的采集站, 这些需要自己去了解, 内置的也有一些采集站, 直接使用也可以
> 
> 问题有一些电影，看着看着就卡着了，而且跳不过去，比如https://m.mubai.link/play?id=82276&source=0&episode=0 7分多 就卡着了 过不去了

这个卡顿一般和访问设备使用的网络以及视频存储服务器那边有关，试下换个网络环境
