### ISSUE TITLE
api 容器 film-film 重启后后台自动更新失效

### ISSUE THREAD

**Issue by DDToms** [ProudMuBai/GoFilm#32]
执行时间0001-01-01 00:00:00
变成这样

![57bfcf3da58499ba2a713d0ef29e184](https://github.com/ProudMuBai/GoFilm/assets/107248199/2e2f3ca2-5752-4f52-8100-7f468fa76dd1)

**Comment by ProudMuBai** [comment]
这个是之前有次更新把启动前的定时任务开启选项给漏了, 已经修复了, 今天晚上我上传一下新版本就好了
