### ISSUE TITLE
导航分类信息获取失败

### ISSUE THREAD

**Issue by sparksworld** [ProudMuBai/GoFilm#34]
- 按照步骤一步步安装的，等了好久还是提示导航分类信息获取失败

**Comment by sparksworld** [comment]
![image](https://github.com/ProudMuBai/GoFilm/assets/27796700/795ed095-2ec7-49e2-a545-e12eeea05771)

**Comment by ProudMuBai** [comment]
可以TG联系我, 我帮你联调一下

**Comment by sparksworld** [comment]
@ProudMuBai 我TG与你沟通了
