### ISSUE TITLE
关于服务器繁忙，请稍后再试

### ISSUE THREAD

**Issue by hawkjjyy** [ProudMuBai/GoFilm#37]
首先非常感谢作者开源gofilm，平台的采集功能很强大。
我反映一个问题。刚开始部署好以后，可以进行正常的采集，但是随着采集量增加，尤其是对主站点进行全量采集后，就会出现“服务器繁忙，请稍后再试”，请问这个怎么解决。

**Comment by ProudMuBai** [comment]
这个提示信息一般是serve端的异常信息，可以看看有没有容器异常终止，需要具体排错可以私聊我TG

**Comment by hawkjjyy** [comment]
收到 ，所有容器全部重启后页面也打不开了。

**Comment by hawkjjyy** [comment]
服务器重启后，故障依旧。

**Comment by ProudMuBai** [comment]
> 服务器重启后，故障依旧。

你私聊我提供截图和相关报错信息，或者留一下你自己的联系方式

**Comment by psk107520** [comment]
你这个咋解决的？我也碰到了一样的问题
