### ISSUE TITLE
请问有做seo优化吗

### ISSUE THREAD

**Issue by biostome** [ProudMuBai/GoFilm#4]
请问有做seo优化吗

**Comment by ProudMuBai** [comment]
这个暂时没有针对这个优化,毕竟为了访问速度和加载效果本身页面很多都是异步请求,并没有那么频繁的去进行页面切换刷新,所以即使做SSR渲染也不会有太大效果,如果要做seo优化可能会将网络请求变得多次且频繁,侧重点不同吧
