### ISSUE TITLE
电脑能进行访问而手机无法进行连接访问

### ISSUE THREAD

**Issue by 328477124** [ProudMuBai/GoFilm#40]
你好，项目进行部署到服务器上了，但是现在根据ip地址进行访问，使用电脑可以进行访问，但是使用手机(也试过切换到桌面)通过ip却不能进行访问，无法进行连接

**Comment by ProudMuBai** [comment]
@328477124 可以试一下其他手机环境，服务器不太可能出现只能由pc端访问的情况，需要排查的话可以私我TG

**Comment by 328477124** [comment]
谢谢，问题解决了！

**Comment by 328477124** [comment]
你好，请问你的tg账号是？我想要吧这个前端进行整合一下添加仓库进行管理，可以聊聊嘛？

**Comment by ProudMuBai** [comment]
@328477124  我的TG账号主页有: @MuBaiCs, 你要整合的话可以上传到自己的存储库进行修改和DIY的, 也希望大家能做出不一样的效果和新的功能出来

**Comment by 328477124** [comment]
好的，作者大大，我很喜欢这个项目😘
