### ISSUE TITLE
关于后台页面无数据显示

### ISSUE THREAD

**Issue by 2803644497** [ProudMuBai/GoFilm#42]
首先非常感谢大佬开源GoFilm项目！
对于刚刚入门go语言的我来说提供了巨大的参考价值，其中的功能模块做得确实强大。
前天参考Markdown文档教程搭建起来了，但今天突然出现了标题所描述的问题，如下图：

<img width="975" alt="Snipaste_2024-04-08_18-35-22" src="https://github.com/ProudMuBai/GoFilm/assets/86231684/9218d9e0-73e4-4aee-a72f-5d4ced212820">

使用网页的开发者工具其实返回的是有数据的，但页面上并没有显示，特向大佬求教

<img width="460" alt="Snipaste_2024-04-08_20-08-17" src="https://github.com/ProudMuBai/GoFilm/assets/86231684/39def5cf-a12c-4d7d-b4da-d587d6ef6f87">

**Comment by AbelCccn** [comment]
是不是替换过film/data/nginx/html目录下 的文件 ？是的话用原文件替换回来就好了

**Comment by 2803644497** [comment]
是的，已按照您的方法解决，谢谢
