### ISSUE TITLE
我部署在虚拟机里，为什么只能虚拟机内访问？宿主机也能访问，但是网页内容不加载，这是那里配置又问题？

### ISSUE THREAD

**Issue by AbelCccn** [ProudMuBai/GoFilm#43]
我部署在虚拟机里，为什么只能虚拟机内访问？宿主机也能访问，但是网页内容不加载，这是那里配置又问题？

**Comment by ProudMuBai** [comment]
这个原因有多种可能需要提供下具体的报错信息才能进行排查, 一般来说虚拟机需要配置自身的端口和物理主机的端口进行映射后才能被局域网内的其他设备访问到的, 至于网页无法加载需要查看浏览器控制台network的报错信息才能进行排查的. 有需要可以私聊我主页TG

**Comment by AbelCccn** [comment]
> 这个原因有多种可能需要提供下具体的报错信息才能进行排查, 一般来说虚拟机需要配置自身的端口和物理主机的端口进行映射后才能被局域网内的其他设备访问到的, 至于网页无法加载需要查看浏览器控制台network的报错信息才能进行排查的. 有需要可以私聊我主页TG

已解决 是浏览器问题，win7上的chrome版本太老，不支持某些特性，换火狐浏览器就解决了！放行端口后，现在外网也能访问了。
