### ISSUE TITLE
redis.go报错

### ISSUE THREAD

**Issue by a152917** [ProudMuBai/GoFilm#7]
修改/server/config/DataConfig.go后运行go run main.go提示这个

plugin/db/redis.go:20:21: syntax error: unexpected literal .0 in composite literal; possibly missing comma or }

**Comment by ProudMuBai** [comment]
可以截图提供下你修改的DataConfig.go的内容吗, 这个报错可能是修改的redis连接地址格式问题或者是修改的时候误删了一些 ,  } 等符号
