### ISSUE TITLE
有没有考虑用 python 开发

### ISSUE THREAD

**Issue by 2023hanjianlin** [ProudMuBai/GoFilm#8]
感觉 python 开发 感觉更快速

**Comment by gudukuaile** [comment]
有没有大佬改个python后端，学习go还来得及不

**Comment by ProudMuBai** [comment]
原理都差不多, 都是对数据进行采集和处理, 各有各的优势吧, 前后端交互都是JSON格式数据, 对后端语言也没啥限制
