### ISSUE TITLE
请求添加一个定时弹窗的功能

### ISSUE THREAD

**Issue by xcoder119** [ProudMuBai/GoFilm#9]
非常感谢作者大大创建了一个这么优秀的项目！
另外能否请求作者大大添加一个定时弹窗的功能，自建了一个给家里孩子看动漫，但又不希望他看太久太伤眼睛，就希望间隔30分钟弹出一个提示框，类似“你当前已持续观看了30分钟，注意休息一下”，无论他当前处于什么页面，都强制弹出。希望大佬能采纳，再次感谢！！

**Comment by ProudMuBai** [comment]
我暂时写了一个固定版本的, 大概效果就是在util组件中, 也就是网站打开时进行倒计时, 45 分钟后会进行一次弹窗, 弹窗关闭后会重新打开一个倒计时, 具体时间和提示语句如果要修改的话在 client/src/components/Popup/CustomDialog.vue 文件中进行相关修改, 也可以 直接使用现在的 dev 分支下 的 client/dist 目录 中的内容替换掉 nginx 的 html 文件夹中内容, 这个组件作为一个可选组件, 目前放在 client/src/components/Util.vue 文件中, 后面可能会先注释掉 需要开启的话取消注释就行 , 等后台开始开发时就会作为后端参数进行控制

**Comment by xcoder119** [comment]
非常感谢作者大大采纳我的需求并给出了实现的方法！
在等待你回复的这几天时间里，我找到了一种相对简单的实现的方法，过程如下

1. 将文件 film/data/nginx/html/assets/index-6cec7a59.js，复制到本地使用 VSCode打开，并格式化(把压缩过的js代码展开)

2.定位到 60588行，插入以下Javascript代码
  ```
window.alert = function(name){
    var iframe = document.createElement("IFRAME");
    iframe.style.display="none";
    document.documentElement.appendChild(iframe);
    window.frames[0].window.alert(name);
    iframe.parentNode.removeChild(iframe);
  };
// 使用setInterval函数每隔一段时间执行一次函数
setInterval(function() {

  // 获取id为"vjs_video_3_html5_api"的视频元素
  var videoElement = document.getElementById("vjs_video_3_html5_api");

  // 如果视频元素存在并且它没有被暂停播放且未结束
  if (videoElement && !videoElement.paused && !videoElement.ended) {

    // 暂停视频播放
    videoElement.pause();

    // 显示一个警告，提示用户已经连续观看了45分钟，建议休息一下
    alert('你已经连续观看了45分钟，请注意休息一下哦');
  }
}, 2700000); // 设置定时器的时间间隔为2700000毫秒，即45分钟
```
![image](https://github.com/ProudMuBai/GoFilm/assets/60035990/b19cb84c-ac77-49f9-9b89-f4f2c6422c93)


3.保存修改后的 index-6cec7a59.js，并覆盖源文件即可

同时我也对比了你给出的实现方法，为了测试效果时缩短等待时间，我把你的源代码中的45分钟改为了20秒，发现弹窗在其他页面能常显示，但是当我将播放器全屏最大化的时候则无法正显示弹窗，也许存在某些bug。。。。
我还是采用了自己写的方法，修改 index-6cec7a59.js后，弹窗在任何界面都可以定时弹出，不存在bug
无论如何还是感谢作者大大采纳了我的需求，并给出了解决的方法，谢谢！

**Comment by ProudMuBai** [comment]
嗯, 好的, 后面我再测试完善一下这个问题
